[tools]
selene = { source = "Kampfkarren/selene", version = "0.22.0" }
rojo = { source = "rojo-rbx/rojo", version = "=7.3.0" }
remodel = { source = "rojo-rbx/remodel", version = "0.9.0" }
wally = { source = "UpliftGames/wally", version = "0.3.1" }
stylua = { source = "JohnnyMorganz/stylua", version = "0.17.1" }